version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/deploy/node-koa-docker-travis-ci-cd-exam # S3에서 가지고온 파일을 저장할 디렉터리 지정
permissions:
    - object: /home/ec2-user
        owner: ec2-user
        group: ec2-user
        mode: 755
        type:
            - directory
            - file
hooks:
  AfterInstall: # 배포가 끝나면 아래 명령어를 실행
    - location: execute-deploy.sh
      timeout: 180
